apiVersion: v1
kind: PersistentVolume
metadata:
  name: odsc-ml-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/dev/Luis/odsc/AirflowKubernetes/dataswati/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odsc-ml-data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
